using AutoWikiBrowser.Plugins.Kingbotk;
using AutoWikiBrowser.Plugins.Kingbotk.Components;
using AutoWikiBrowser.Plugins.Kingbotk.ManualAssessments;
using AutoWikiBrowser.Plugins.Kingbotk.Plugins;
using My;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Diagnostics;
using System.Text.RegularExpressions;
using System.Windows.Forms;
using System.Xml;
using WikiFunctions;
using WikiFunctions.Logging.Uploader;
using WikiFunctions.Plugin;
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace My.Resources
{

	//This class was auto-generated by the StronglyTypedResourceBuilder
	//class via a tool like ResGen or Visual Studio.
	//To add or remove a member, edit your .ResX file then rerun ResGen
	//with the /str option, or rebuild your VS project.
	///<summary>
	///  A strongly-typed resource class, for looking up localized strings, etc.
	///</summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute(), Microsoft.VisualBasic.HideModuleNameAttribute()]
	static internal class Resources
	{

		private static global::System.Resources.ResourceManager resourceMan;

		private static global::System.Globalization.CultureInfo resourceCulture;

		///<summary>
		///  Returns the cached ResourceManager instance used by this class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		static internal global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources", typeof(Resources).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}

		///<summary>
		///  Overrides the current thread's CurrentUICulture property for all
		///  resource lookups using this strongly typed resource class.
		///</summary>
		[System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		static internal global::System.Globalization.CultureInfo Culture {
			get { return resourceCulture; }
			set { resourceCulture = value; }
		}

		///<summary>
		///  Looks up a localized string similar to Copyright © 2008 Stephen Kennedy (Kingboyk) http://www.sdk-software.com/
		///Copyright © 2008 Sam Reed (Reedy) http://www.reedyboy.net/
		///
		///This program is free software; you can redistribute it and/or modify it under the terms of Version 2 of the GNU General Public License as published by the Free Software Foundation.
		///
		///This program is distributed in the hope that it will be useful,
		///but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GN [rest of string was truncated]&quot;;.
		///</summary>
		static internal string GPL {
			get { return ResourceManager.GetString("GPL", resourceCulture); }
		}

		static internal System.Drawing.Bitmap king_worship1 {
			get {
				object obj = ResourceManager.GetObject("king_worship1", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}

		static internal System.Drawing.Bitmap WP1 {
			get {
				object obj = ResourceManager.GetObject("WP1", resourceCulture);
				return (System.Drawing.Bitmap)obj;
			}
		}
	}
}
