name: awb

on: [push, pull_request]

jobs:
  build-windows:
    name: Windows
    runs-on: ${{ matrix.windows-version }}
    strategy:
      fail-fast: false
      matrix:
        windows-version: ['windows-2019']

    steps:
      - uses: actions/checkout@v3.3.0
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1
      - name: Build
        run: |
            MSBuild.exe $Env:GITHUB_WORKSPACE\'AutoWikiBrowser no plugins.sln' /p:Configuration=Release
      - name: Upload artifacts
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ${{ matrix.windows-version }}
          path: AWB/bin/Release
