name: awb

on: [push, pull_request]

jobs:
  build-windows:
    name: Windows
    runs-on: ${{ matrix.windows-version }}
    strategy:
      fail-fast: false
      matrix:
        windows-version: ['windows-2022']

    steps:
      - uses: actions/checkout@v4
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Restore NuGet
        uses: nuget/setup-nuget@v2
        run: nuget restore 'AutoWikiBrowser no plugins.sln'
      - name: Build
        run: |
            MSBuild.exe $Env:GITHUB_WORKSPACE\'AutoWikiBrowser no plugins.sln' /p:Configuration=Release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.windows-version }}
          path: AWB/bin/Release
